name: bert_untrain_2
type: encoder

model_path: ${hydra:runtime.cwd}/../checkpoints/no_pretrain_2_layer/
output_dim: 768
layer_num: 16
layer_to_probe: 2
vocab_size: 32768

save_path: ${hydra:runtime.cwd}/../models/${wandb.name}