name: bert_untrain_16
type: encoder

model_path: ${hydra:runtime.cwd}/../checkpoints/no_pretrain_16_layer/
output_dim: 768
layer_num: 16
layer_to_probe: 16
vocab_size: 32768

save_path: ${hydra:runtime.cwd}/../models/${model.name}