defaults:
  - tasks:
    - pos
    - const
    - ner
    - srl
    - coref
    - rc

data_path: /localdisk/data1/Data/processed_ontonotes/

save_intermediates: false
freeze_subject: false

# not useful, different for each sub task
num_classes: 1
single_span: true
concat: false