name: named_entity_recognition
data: ontonotesv5

save_intermediates: false
freeze_subject: true
data_path: /localdisk/data1/Data/processed_ontonotes/

# Training Parameters
batch_size: 64
epochs: 10
learning_rate: 1e-4
gradient_accumulation_steps: 1
early_stopping_patience: 5
min_delta: 0.001
gradient_clip: 5.0
train_size: 1 # percentage of training data to use each epoch

# Task Specific Parameters
num_classes: 19
single_span: true
concat: false # whether to concatenate the first and current hidden states

# Data
train_file: ${task.data_path}/ner/ner_train_processed.parquet
val_file: ${task.data_path}/ner/ner_val_processed.parquet
test_file: ${task.data_path}/ner/ner_test_processed.parquet