name: pos_tagging
data: ontonotesv5

# Training Parameters
batch_size: 64
epochs: 10
learning_rate: 1e-4
gradient_accumulation_steps: 1
early_stopping_patience: 5
min_delta: 0.001
gradient_clip: 5.0
train_size: 0.2 # percentage of training data to use each epoch

# Task Specific Parameters
num_classes: 51
single_span: true
concat: true # whether to concatenate the first and current hidden states

# Data
train_file: ${hydra:runtime.cwd}/../dataset/ontonotesv5/train_processed.parquet
val_file: ${hydra:runtime.cwd}/../dataset/ontonotesv5/val_processed.parquet
test_file: ${hydra:runtime.cwd}/../dataset/ontonotesv5/test_processed.parquet